### ISSUE TITLE
How to construct complex mesh properly?

### ISSUE THREAD

**Issue by mxposed** [janba/GEL#14]
Hello. Thank you for the library.
I'm trying to use it to get signed distance from points in 3d to convex hull, however I'm having trouble with that.

This is a simple random convex hull
```python
import numpy as np
from scipy.spatial import ConvexHull

mat = np.random.rand(30,3)
hull = ConvexHull(mat)
```

I then construct the mesh:
```python
m = gel.Manifold()
for s in hull.simplices:
    m.add_face(hull.points[s])
```

And measure distance from all the original points used to create the convex hull:
```python
dist = gel.MeshDistance(m)
res = []
for p in mat:
    res.append(dist.signed_distance(p))
```

However, the distances get both positive and negative, while they should be only negative (since all points are inside the hull).
I think the problem is with the construction of the mesh, because all the faces are separate and vertices as well. I tried to create algorithm to stitch faces together, but I'm having trouble writing it.
I would be glad to hear your advice

**Comment by janba** [comment]
Hello MXPosed,

See the code below for a bit of context for this response.

Everything is actually working, but it appears that qhull does not guarantee that the simplicial faces are all counter clockwise (i.e. the three vertices in each face are not necessarily in the right CCW order). I did not check the documentation, but if you visualise the hull it becomes apparent that some faces are turning the other way (dark). I also added annotation points for all of the points which is helpful for showing that the polytope is indeed the convex hull.

If you don't really care whether the mesh is consistent, but you do want to know whether each point is inside, you can use the ray intersection inside/outside test for these cases.

However, note that the mesh is not watertight if the orientation is not consistent. This might be unfortunate depending on your downstream use of the mesh...

Best
Andreas

```
from PyGEL3D import gel
import numpy as np
from scipy.spatial import ConvexHull

mat = np.random.rand(30, 3)
hull = ConvexHull(mat)

m = gel.Manifold()
for s in hull.simplices:
    m.add_face(list(hull.points[s]))

viewer = gel.GLManifoldViewer()
viewer.set_annotation_points(mat)
viewer.display(m, mode='g', smooth=False)

dist = gel.MeshDistance(m)
for p in mat:
    d = dist.signed_distance(p)
    s = dist.ray_inside_test(p)
    print("point and dist ", p, d, " and inside test: ", s)
```

**Comment by mxposed** [comment]
Thank you very much!
The `ray_inside_test` method does the trick.

Below are couple of theoretical questions, if you deem them interesting and would have time for them.
The `qhull` indeed does not guarantee a CCW order of points. Do I get it right that if I would reorder vertices for each simplex to be in CCW order, the `signed distance` would output the correct (I mean expected) sign for every point? Would it also make the mesh watertight?
What does it matter if the mesh is watertight or not? And does it matter if two adjacent faces share vertices and edges, or each has its own set?

Thank you,
Best regards,
Nick

**Comment by janba** [comment]
Hi Nick,


The qhull indeed does not guarantee a CCW order of points. Do I get it right that if I would reorder vertices for each simplex to be in CCW order, the signed distance would output the correct (I mean expected) sign for every point? Would it also make the mesh watertight?

Yes to both questions. However, you also need to call stitch:

http://www2.compute.dtu.dk/projects/GEL/PyGEL/PyGEL/gel.m.html#PyGEL3D.gel.stitch

before using the mesh for distance computations. This is what makes it watertight. Let us define watertight as being when there are no holes in the mesh and two triangle corners at the same geometric position must be the same vertex. stitch welds together triangle corners that coincide. You can also create the mesh using from_triangles although I see this is not documented, but the from_triangles class method will stitch.


What does it matter if the mesh is watertight or not? And does it matter if two adjacent faces share vertices and edges, or each has its own set?


This depends very much on your application. If you want to smooth, subdivide or deform the mesh, it is essential that vertices shared by two faces are actually the same vertex since it is otherwise very likely that visible holes appear when your algorithm changes the mesh.

Even if you want to just render the mesh as a smooth surface, the vertex normals can also only be computed correctly if the mesh is watertight in this sense.The sign of my distance computation also relies on vertex normals being correct. The ray test is really a kludge for a specific set of cases where the surface cannot be orientated correctly.

Best
Andreas


On 3 Apr 2019, at 00.11, Nikolay Markov <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you very much!
The ray_inside_test method does the trick.

Below are couple of theoretical questions, if you deem them interesting and would have time for them.
The qhull indeed does not guarantee a CCW order of points. Do I get it right that if I would reorder vertices for each simplex to be in CCW order, the signed distance would output the correct (I mean expected) sign for every point? Would it also make the mesh watertight?
What does it matter if the mesh is watertight or not? And does it matter if two adjacent faces share vertices and edges, or each has its own set?

Thank you,
Best regards,
Nick

**Comment by mxposed** [comment]
Hi Andreas,
Thank you very much for the explanations!
I understand the kludge well (and it's good that you have it), and since this helped to solve the problem at hand, I haven't looked into this yet. But next time I get to this, I hope to reorder `qhull` faces in CCW and call `stitch`. Thank you
