### ISSUE TITLE
GEL::centre

### ISSUE THREAD

**Issue by timfelle** [janba/GEL#28]
Is it a misspelling that the function to compute the center of a face is called "centre" rather than "center", and would it be possible with an overload to compute the center of an edge?

**Comment by janba** [comment]
Right. Actually, `centre` is both British spelling and imprecise - since it could conceivably mean e.g. the center of the circumcircle. I made a new function `barycenter` that is overloaded for half edges and faces. For faces it returns the same as `centre` which is still there for backwards compatibility.
