### ISSUE TITLE
Smooth.cpp : TAL_smoothing . NaN issue with overlapping vertices

### ISSUE THREAD

**Issue by RasmusRPaulsen** [janba/GEL#33]
{
                            Vec3d vec_a = normalize(m.pos(w.vertex()) - m.pos(*vid));
                            Vec3d vec_b = normalize(m.pos(w.circulate_vertex_ccw().vertex()) -
                                                    m.pos(*vid));
                            angle_sum += acos(max(-1.0,min(1.0,dot(vec_a,vec_b))));
                        }

Behaves very badly if there are overlapping vertices. It happens in normalize that assumes a non-zero distance between vertices.

Since this is an iterative smoothing process, overlapping vertices DO happen from time to time.

A solution is:
 {
                            Vec3d vec_a = m.pos(w.vertex()) - m.pos(*vid);
                            Vec3d vec_b = m.pos(w.circulate_vertex_ccw().vertex()) - m.pos(*vid);
                            if (vec_a.length() && vec_b.length())
                            {
                                vec_a = normalize(vec_a );
                                vec_b = normalize(vec_b);
                                angle_sum += acos(max(-1.0, min(1.0, dot(vec_a, vec_b))));
                            }
 }

**Comment by janba** [comment]
TAL_smoothing was a terrible, terrible function. It used cotangent weights which is probably not a good idea since these weights are for smoothing geometry without smoothing the parametrisation (too much), but tangential area weighted laplacian smoothing is used to smooth the parametrisation while not changing the geometry too much. It also looked like the tangential part was missing ...

I have changed the function in the following way:
- It now uses some more recent GEL functions for mesh traversal.
- It does not move boundary vertices. 
- It uses the regular Laplacian - i.e. moves vertices towards the barycentre of their neighbours (weighted by their area), but before moving the vertices, it projects the Laplacian into the tangent plane in order to not change the geometry more than it has to. I think this behaviour is the desired and on the tested meshes it looks fairly good. It definitely smooths much less than Taubin smoothing or straight Laplacian smoothing, and it equalises areas better. See below for an example where a mesh is shown followed by 10 iterations of TAL smoothing and below 10 iterations of Taubin smoothing (applied to the original mesh). It is clear that TAL preserves geometry better while equalising area more than Taubin. 

<img width="585" alt="image" src="https://user-images.githubusercontent.com/3034947/97106894-925e8080-16c4-11eb-8ef5-cf321728c181.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3034947/97106912-a7d3aa80-16c4-11eb-9363-e59948c34f7c.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3034947/97106922-b4580300-16c4-11eb-9f8d-f51a80ce0482.png">

I am making some additions to GEL to make it possible to use range based for loops instead of circulation to get the neighbours of vertices and faces. This function will be part of the update coming later today.
