### ISSUE TITLE
Point cloud to skeleton

### ISSUE THREAD

**Issue by kdmarrett** [janba/GEL#60]
Incredible library and paper!

I have point cloud/voxel grid data that is very similar to the botanical tree used in the SIGGRAPH local separators. 

Can you point me to or share the snippet/script of code you used to accomplish the point cloud to graph pipeline mentioned in section 3.4 of the paper. There are several details to get right in that conversion, so I'd like to start from your exact implementation to reproduce the same high quality skeletons shown in the paper.

Thank you

**Comment by janba** [comment]
Hi Karl,

Thanks for your kind words.

the simple algorithm in 3.4 was not implemented in a script but manually on the command line via three simple commands:

1. The first step is simply to connect all points to neighbours within a given radius. This is simple to accomplish using a kD tree (and there is one in GEL).

2. The second step is unfortunately not exposed in Python but it is in the C++ interface. It is the saturate_graph function. This step is really important since it increases the connectivity and thereby simplifies the skeleton. Without it you might have a very complex skeleton with spurious loops. If you have points on a voxel grid, however, this pipeline is not helpful. Instead you should connect each point to its 26 neighbours in the 3x3x3 neighbourhood.

3. The final step is to simplify the graph via edge contraction. This is exposed in the Python interface. Simplification is also important because otherwise skeletonization can take a while. We have a much faster (hierarchical) skeletonization implementation under review but it is not yet exposed in the main branch of GEL.

In preparation for my spring course, I will merge the hierarchical version of the skeletonization and a number of other improvements into the main branch, so simplification might become superfluous soon.

Best
Andreas




On 2 Jan 2023, at 00.13, Karl Marrett ***@***.***> wrote:



Incredible library and paper!

I have point cloud/voxel grid data that is very similar to the botanical tree used in the SIGGRAPH local separators.

Can you point me to or share the snippet/script of code you used to accomplish the point cloud to graph pipeline mentioned in section 3.4. There are several details to get right in that conversion, so I'd like to start from your exact implementation to reproduce the same high quality skeletons shown in the paper.

Thank you

**Comment by kdmarrett** [comment]
Much appreciated, due to large scale and performance concerns I converted the point clouds into a quad mesh, as mentioned in my latest issue.
Thank you again for the help.
