### ISSUE TITLE
How to load a custom graph to pygel3d.graph.Graph object

### ISSUE THREAD

**Issue by Paddy-Xu** [janba/GEL#64]
Hi, 

Thanks for the great work! I am trying to use the `hmesh.skeleton_to_feq` function to turn a skeleton graph to Face Extrusion Quad Mesh. But for this, I need a  pygel3d.graph.Graph object first. 

I have a custom graph where for each node, I know its xyz coordinate as well as a node radius. Besides, I also have an edge (connections) array where each row represents the two indices of two connected nodes. It is currently modeled networkx + pyvista, but I can easily change it to other modelling. 

Is there a way to save the data to the format that can be loaded by `graph.load`. Otherwise, can I directly create a `pygel3d.graph.Graph` object by adding nodes and edges? I can only see a` add_node` function but seem not able to find how to integrate connections?

**Comment by janba** [comment]
Hi

I think that all you need is the connect_nodes function:

https://www2.compute.dtu.dk/projects/GEL/PyGEL/PyGEL/pygel3d/graph.html

However, it is also very easy to write a file that can be loaded. The lines look as shown below. Nodes are in lines that start with ‘n’. The three numbers are its spatial coordinates. Lines starting with ‘c’ contain edges. The two integers are indices of the nodes connected by the edge.
---
n -53.4465 67.5229 -55.6761
n 50.4145 88.7568 -30.7732
n 26.2273 -50.9661 -0.671426
c 0 21
c 1 46
c 2 3

A bunch of work is going into the feq conversion. It is not done yet, but if you want to try it out, you could checkout the experimental2 branch.




From: PadX ***@***.***>
Date: Monday, 3 July 2023 at 14.39
To: janba/GEL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [janba/GEL] How to load a custom graph to pygel3d.graph.Graph object (Issue #64)

Hi,

Thanks for the great work! I am trying to use the hmesh.skeleton_to_feq function to turn a skeleton graph to Face Extrusion Quad Mesh. But for this, I need a pygel3d.graph.Graph object first.

I have a custom graph where for each node, I know its xyz coordinate as well as a node radius. Besides, I also have an edge (connections) array where each row represents the two indices of two connected nodes. It is currently modeled networkx + pyvista, but I can easily change it to other modelling.

Is there a way to save the data to the format that can be loaded by graph.load. Otherwise, can I directly create a pygel3d.graph.Graph object by adding nodes and edges? I can only see a add_node function but seem not able to find how to integrate connections?
